'use client';

import React, { useState, useEffect } from 'react';
import { mockStore } from '@/lib/data/mockStore';
import { User, CommissionRecord } from '@/types';
import { Gift, ShieldCheck, CheckCircle2, AlertCircle, Users, DollarSign, Calendar } from 'lucide-react';

export default function GenerationBonusPage() {
  const [user, setUser] = useState<User | null>(null);
  const [commissions, setCommissions] = useState<CommissionRecord[]>([]);

  const refreshData = () => {
    const active = mockStore.getActiveUser();
    setUser(active);
    if (active) {
      setCommissions(mockStore.getCommissions(active.id));
    }
  };

  useEffect(() => {
    refreshData();
  }, []);

  if (!user) return null;

  const totalCommissionsEarned = commissions.reduce((sum, c) => sum + c.amount, 0);

  return (
    <div className="flex flex-col gap-8 pb-12">
      {/* Header Banner */}
      <div className="glass-panel-gold rounded-2xl p-6 border border-gold-500/30 flex flex-col md:flex-row md:items-center justify-between gap-6 shadow-[0_0_25px_rgba(212,175,55,0.12)]">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-gold-500/20 border border-gold-500/40 text-gold-300 text-xs font-semibold mb-2">
            <Gift className="w-3.5 h-3.5" /> Generation-1 40% Daily Trading Income Bonus (SRS §3.3)
          </div>
          <h1 className="text-2xl md:text-3xl font-extrabold text-white">Generation-1 Commission Ledger</h1>
          <p className="text-sm text-silver-300 mt-1">
            Eligible Level-1 sponsors receive 40% of the daily trading profit generated by direct (Gen-1) team members.
          </p>
        </div>

        <div className="bg-obsidian-900/80 border border-gold-500/30 px-6 py-4 rounded-xl flex items-center gap-4">
          <div className="p-3 bg-purple-500/20 text-purple-400 rounded-xl border border-purple-500/40">
            <Gift className="w-6 h-6" />
          </div>
          <div>
            <p className="text-xs text-gold-300 font-bold uppercase tracking-wider">Total Commission Earned</p>
            <p className="text-2xl font-black text-gold-400">${totalCommissionsEarned.toFixed(2)}</p>
          </div>
        </div>
      </div>

      {/* Qualification Alert Banner */}
      <div className={`p-5 rounded-2xl border flex items-center justify-between ${user.level1Qualified ? 'bg-emerald-500/10 border-emerald-500/30 text-emerald-300' : 'bg-amber-500/10 border-amber-500/30 text-amber-300'}`}>
        <div className="flex items-center gap-3">
          {user.level1Qualified ? <CheckCircle2 className="w-6 h-6 text-emerald-400 shrink-0" /> : <AlertCircle className="w-6 h-6 text-amber-400 shrink-0" />}
          <div>
            <h3 className="text-sm font-bold text-white">
              {user.level1Qualified ? 'Level-1 Sponsor Qualified (Active)' : 'Level-1 Sponsor Requirements Pending'}
            </h3>
            <p className="text-xs text-silver-400 mt-0.5">
              {user.level1Qualified
                ? 'Your account is actively earning 40% commissions on all eligible direct member daily trading profits.'
                : 'Complete Level-1 requirements ($\ge \$500$ personal investment + 4 direct referrals with $\ge \$500$) to start receiving commissions.'}
            </p>
          </div>
        </div>
        <span className="text-xs font-mono font-bold px-3 py-1 rounded bg-obsidian-900/80 border border-obsidian-750">
          Rate: 40.0%
        </span>
      </div>

      {/* Commission Ledger Table */}
      <div className="glass-panel rounded-2xl p-6 border border-obsidian-750">
        <h3 className="text-base font-bold text-white mb-4">First-Generation Commission History</h3>
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs text-silver-300">
            <thead className="bg-obsidian-850 text-silver-400 uppercase font-bold text-[10px] tracking-wider border-b border-obsidian-750">
              <tr>
                <th className="p-3.5">Commission ID</th>
                <th className="p-3.5">Direct Member Name</th>
                <th className="p-3.5">Member Daily Profit</th>
                <th className="p-3.5">Commission Rate</th>
                <th className="p-3.5">Payout Amount</th>
                <th className="p-3.5">Generation Scope</th>
                <th className="p-3.5">Status</th>
                <th className="p-3.5">Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-obsidian-800">
              {commissions.map(comm => (
                <tr key={comm.id} className="hover:bg-obsidian-850/60 transition-all">
                  <td className="p-3.5 font-mono text-gold-300 font-bold">{comm.id}</td>
                  <td className="p-3.5 font-bold text-white flex items-center gap-2">
                    <Users className="w-3.5 h-3.5 text-purple-400" />
                    {comm.sourceMemberName}
                  </td>
                  <td className="p-3.5 font-mono text-silver-300">${comm.sourceProfitAmount.toFixed(2)}</td>
                  <td className="p-3.5 font-mono font-bold text-gold-400">{(comm.rate * 100).toFixed(0)}%</td>
                  <td className="p-3.5 font-mono font-extrabold text-emerald-400 text-sm">+${comm.amount.toFixed(2)}</td>
                  <td className="p-3.5">
                    <span className="bg-obsidian-800 text-silver-300 border border-obsidian-700 px-2 py-0.5 rounded text-[10px] font-mono">
                      Gen-1 Direct
                    </span>
                  </td>
                  <td className="p-3.5">
                    <span className="inline-flex items-center gap-1 bg-emerald-500/10 text-emerald-400 border border-emerald-500/30 px-2 py-0.5 rounded-md font-bold text-[10px]">
                      <CheckCircle2 className="w-3 h-3" /> {comm.status}
                    </span>
                  </td>
                  <td className="p-3.5 text-silver-400">{new Date(comm.createdAt).toLocaleString()}</td>
                </tr>
              ))}
              {commissions.length === 0 && (
                <tr>
                  <td colSpan={8} className="p-8 text-center text-silver-500">
                    No generation commission records logged yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
